# Generated by Django 5.0.6 on 2024-06-05 10:10

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, null=True)),
                ('password', models.CharField(max_length=516, null=True)),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.IntegerField(choices=[(-3, '待激活'), (-2, '异常'), (-1, '注销'), (0, '正常'), (1, '封号')], default=-3)),
                ('nickname', models.CharField(default='es_4kHnHqj8_20240605_d84bb08', max_length=40, unique=True)),
                ('avatar', models.FileField(null=True, upload_to='avatar/')),
                ('mobile', models.CharField(blank=True, max_length=13, null=True)),
                ('email', models.CharField(blank=True, max_length=70, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', '男'), ('F', '女')], max_length=1, null=True)),
                ('description', models.TextField(max_length=200, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('official_id', models.CharField(max_length=70, null=True)),
                ('last_update_time', models.DateTimeField(auto_now=True, null=True)),
                ('political_affiliation', models.CharField(choices=[('群众', '群众'), ('团员', '团员'), ('党员', '党员'), ('预备党员', '预备党员'), ('共青团员', '共青团员'), ('无党派人士', '无党派人士'), ('民主党派', '民主党派'), ('宗教', '宗教'), ('其他', '其他')], default='群众', max_length=70, null=True)),
                ('ethnicity', models.CharField(max_length=20, null=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='user_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='user_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('ip', models.CharField(blank=True, max_length=100, null=True)),
                ('ua', models.CharField(blank=True, max_length=200, null=True)),
                ('log_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': '登录日志',
                'verbose_name_plural': '登录日志',
                'db_table': 'login_log',
            },
        ),
        migrations.CreateModel(
            name='OpLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('re_ip', models.CharField(blank=True, max_length=100, null=True)),
                ('re_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('re_url', models.CharField(blank=True, max_length=200, null=True)),
                ('re_method', models.CharField(blank=True, max_length=10, null=True)),
                ('re_content', models.CharField(blank=True, max_length=200, null=True)),
                ('access_time', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'db_table': 'op_log',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=70)),
                ('parent_role_id', models.IntegerField(default=-1, null=None)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(-2, '异常'), (0, '正常'), (1, '封禁')], default=0)),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='UserSubTablesTEA',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('office_location', models.CharField(blank=True, max_length=200, null=True)),
                ('research_interests', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '用户教师附表',
                'verbose_name_plural': '用户教师附表',
                'db_table': 'user_subTable_TEA',
            },
        ),
        migrations.CreateModel(
            name='UserSubTableSTU',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('institute', models.CharField(max_length=50)),
                ('grade', models.CharField(max_length=50)),
                ('domain', models.CharField(max_length=50)),
                ('aclass', models.CharField(max_length=50)),
                ('duration', models.IntegerField(default=4)),
                ('enrollment_date', models.CharField(max_length=50, null=True)),
                ('graduation_time', models.CharField(max_length=50, null=True)),
                ('grade_point', models.FloatField(default=0.0, null=True)),
                ('graduation', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name': '用户学生附表',
                'verbose_name_plural': '用户学生附表',
                'db_table': 'user_subTable_STU',
            },
        ),
        migrations.CreateModel(
            name='Dormitory',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('room_number', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('gender_allowed', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('emergency_contact', models.CharField(max_length=70, null=True)),
                ('emergency_contact_phone', models.CharField(max_length=20, null=True)),
                ('health', models.CharField(default='良好', max_length=70, null=True)),
                ('warden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '宿舍',
                'verbose_name_plural': '宿舍',
                'db_table': 'dormitory',
            },
        ),
    ]
