# Generated by Django 5.0.6 on 2024-06-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='es_IY6aW5HO_20240605_ae18e0e', max_length=40, unique=True),
        ),
    ]
