# Generated by Django 5.0.6 on 2024-06-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='es_e68FAUQ8_20240605_47a6529', max_length=40, unique=True),
        ),
    ]
