# Generated by Django 5.0.6 on 2024-06-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='es_VnKSPw6r_20240606_6df88ae', max_length=40, unique=True),
        ),
    ]
