# Generated by Django 5.0.6 on 2024-06-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='es_1jipLZo1_20240606_455f282', max_length=40, unique=True),
        ),
    ]
