# Generated by Django 5.0.6 on 2024-06-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_alter_user_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='dormitory',
            name='user_name',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='dormitory',
            name='warden_name',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='es_cgkFoVuJ_20240608_cd0f57a', max_length=40, unique=True),
        ),
    ]
